name: Workflow 2

on:
  push:
  #workflow_run:
    #workflows: ["Workflow 1"]
    #types:
      #- completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only trigger if Workflow 1 was successful
    runs-on: ubuntu-latest
    steps:
      - name: Echo building
        run: echo "Building in Workflow 2"
